version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:task-definition/MyApp-Task-Def:88"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: "80"
